force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <label>Leave Request</label>
    <nameField>
        <label>Leave Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>In-Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sick</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/leaveRequestSampleData.cls
public with sharing class leaveRequestSampleData {
    @AuraEnabled(cacheable=true)
    public static List<Leave_Request__c> getMyLeaves(){
        try {
            List<Leave_Request__c> leaveList = new List<Leave_Request__c>();
            leaveList = [Select Id,Name,From_Date__c,To_Date__c,Type__c,Status__c FROM Leave_Request__c WHERE User__c=:Userinfo.getuserId() ORDER BY CreatedDate DESC];
            return leaveList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Leave_Request__c> getLeaveRequests(){
        try {
            List<Leave_Request__c> leaveReqList = new List<Leave_Request__c>();
            leaveReqList = [Select Id,Name,From_Date__c,To_Date__c,Type__c,Status__c FROM Leave_Request__c WHERE User__c=:Userinfo.getuserId() ORDER BY CreatedDate DESC];
            return leaveReqList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage()); 
        }
    }

}